<script setup lang="ts">
const workspaces = [
  {
    workspaceId: 'diKp278jEu',
    accountId: 'gtMoV7Isi0',
    workspace: {
      workspaceId: 'diKp278jEu',
      displayName: 'Ростелеком',
      subdomain: 'rostelekom',
      createdAt: '2024-12-23T13:36:26.988Z',
      updatedAt: '2025-10-25T11:39:21.525Z',
      primaryAvatar: {
        avatarId: 'hhpiNO1CVt',
        dominantColor: '8c8c8c',
      },
      membersCount: 12356,
      type: 'UBER',
      organizationId: 'aRhF4Xy4Su',
      notifySettings: null,
    },
    createdAt: '2025-04-21T06:42:37.603Z',
    updatedAt: '2025-04-21T06:42:37.610Z',
    joinedAt: '2025-04-21T06:42:37.610Z',
    notificationsCount: 0,
    roleType: 'MEMBER',
    inviterMemberId: 'diKp28YitE',
    invitedAt: '2025-04-21T06:42:37.600Z',
    permissions: [
      'JOIN_CHAT',
      'INVITE_TO_CHAT',
      'CREATE_PERSONAL_CHAT',
      'SEARCH_CHATS',
      'CREATE_PERSONAL_CHAT_WITH_BOT',
      'CREATE_SHARED_LINK',
      'TOGGLE_CONFERENCE_RECORDING',
      'CREATE_THREAD_IN_PERSONAL_CHAT',
      'INVITE_MEMBER',
    ],
    status: 'ACTIVE',
    memberId: 'gtMoVMdDjU',
    ordernumber: 0,
  },
  {
    workspaceId: 'djxK8s2bNA',
    accountId: 'gtMoV7Isi0',
    workspace: {
      workspaceId: 'djxK8s2bNA',
      displayName: 'Флудилка и support',
      subdomain: 'fludilka-i-support',
      createdAt: '2024-12-24T13:02:50.106Z',
      updatedAt: '2025-10-28T15:42:13.044Z',
      primaryAvatar: null,
      membersCount: 878,
      type: 'REGULAR',
      organizationId: 'aRhF4Xy4Su',
      notifySettings: null,
    },
    createdAt: '2025-04-21T06:55:59.567Z',
    updatedAt: '2025-04-21T06:55:59.609Z',
    joinedAt: '2025-04-21T06:55:59.609Z',
    notificationsCount: 0,
    roleType: 'MEMBER',
    inviterMemberId: 'djxK8stOlM',
    invitedAt: '2025-04-21T06:55:59.563Z',
    permissions: [
      'CREATE_SHARED_LINK',
      'CREATE_THREAD_IN_WORKSPACE_CHAT',
      'CREATE_WORKSPACE_CHAT',
      'CREATE_PERSONAL_CHAT_WITH_BOT',
      'CREATE_THREAD_IN_PERSONAL_CHAT',
      'JOIN_CHAT',
      'SEARCH_CHATS',
      'INVITE_MEMBER',
      'TOGGLE_CONFERENCE_RECORDING',
      'INVITE_TO_CHAT',
    ],
    status: 'ACTIVE',
    memberId: 'gtNliy3WL3',
    ordernumber: 1,
  },
  {
    workspaceId: 'gtby5FwMuO',
    accountId: 'gtMoV7Isi0',
    workspace: {
      workspaceId: 'gtby5FwMuO',
      displayName: 'Вижу Всё',
      subdomain: 'se',
      createdAt: '2025-04-21T10:14:41.601Z',
      updatedAt: '2025-10-28T15:42:13.044Z',
      primaryAvatar: {
        avatarId: 'gtdX7aZqPQ',
        dominantColor: '8c8c8c',
      },
      membersCount: 4,
      type: 'REGULAR',
      organizationId: 'aRhF4Xy4Su',
      notifySettings: null,
    },
    createdAt: '2025-04-21T10:14:41.604Z',
    updatedAt: '2025-04-21T10:14:41.604Z',
    joinedAt: '2025-04-21T10:14:41.603Z',
    notificationsCount: 0,
    roleType: 'OWNER',
    inviterMemberId: '',
    invitedAt: null,
    permissions: [
      'CREATE_PERSONAL_CHAT_WITH_BOT',
      'CREATE_WORKSPACE_CHAT',
      'GRANT_ADMIN',
      'MANAGE_BOT',
      'GRANT_OWNER',
      'CANCEL_INVITE',
      'EDIT_WORKSPACE_NAME',
      'INVITE_TO_CHAT',
      'CREATE_SHARED_LINK',
      'REMOVE_MEMBER',
      'UPDATE_CONFIG',
      'CREATE_THREAD_IN_PERSONAL_CHAT',
      'REVOKE_ADMIN',
      'JOIN_CHAT',
      'REVOKE_OWNER',
      'SEARCH_CHATS',
      'INVITE_MEMBER',
      'TOGGLE_CONFERENCE_RECORDING',
      'MANAGE_WORKSPACE_SHARED_LINKS',
      'CREATE_THREAD_IN_WORKSPACE_CHAT',
    ],
    status: 'ACTIVE',
    memberId: 'gtby5Hdxgm',
    ordernumber: 3,
  },
  {
    workspaceId: 'hj0pa5vxcO',
    accountId: 'gtMoV7Isi0',
    workspace: {
      workspaceId: 'hj0pa5vxcO',
      displayName: 'ЕСУЗ',
      subdomain: 'esuz',
      createdAt: '2025-05-22T09:30:30.137Z',
      updatedAt: '2025-10-28T15:42:13.044Z',
      primaryAvatar: {
        avatarId: 'hkKPWE9hxo',
        dominantColor: '8c8c8c',
      },
      membersCount: 31,
      type: 'REGULAR',
      organizationId: 'aRhF4Xy4Su',
      notifySettings: null,
    },
    createdAt: '2025-05-22T09:30:30.139Z',
    updatedAt: '2025-05-22T09:30:30.139Z',
    joinedAt: '2025-05-22T09:30:30.138Z',
    notificationsCount: 0,
    roleType: 'OWNER',
    inviterMemberId: '',
    invitedAt: null,
    permissions: [
      'CREATE_PERSONAL_CHAT_WITH_BOT',
      'CREATE_WORKSPACE_CHAT',
      'GRANT_ADMIN',
      'MANAGE_BOT',
      'GRANT_OWNER',
      'CANCEL_INVITE',
      'EDIT_WORKSPACE_NAME',
      'INVITE_TO_CHAT',
      'CREATE_SHARED_LINK',
      'REMOVE_MEMBER',
      'UPDATE_CONFIG',
      'CREATE_THREAD_IN_PERSONAL_CHAT',
      'REVOKE_ADMIN',
      'JOIN_CHAT',
      'REVOKE_OWNER',
      'SEARCH_CHATS',
      'INVITE_MEMBER',
      'TOGGLE_CONFERENCE_RECORDING',
      'MANAGE_WORKSPACE_SHARED_LINKS',
      'CREATE_THREAD_IN_WORKSPACE_CHAT',
    ],
    status: 'ACTIVE',
    memberId: 'hj0pa6V9sW',
    ordernumber: 4,
  },
  {
    workspaceId: 'k8YmHbpmJF',
    accountId: 'gtMoV7Isi0',
    workspace: {
      workspaceId: 'k8YmHbpmJF',
      displayName: 'IT-сервисы',
      subdomain: 'it-services',
      createdAt: '2025-08-20T11:58:46.821Z',
      updatedAt: '2025-10-28T15:42:13.044Z',
      primaryAvatar: {
        avatarId: 'k8Ykw07Av2',
        dominantColor: '8c8c8c',
      },
      membersCount: 3,
      type: 'REGULAR',
      organizationId: 'aRhF4Xy4Su',
      notifySettings: null,
    },
    createdAt: '2025-08-20T11:58:46.824Z',
    updatedAt: '2025-08-20T11:58:46.824Z',
    joinedAt: '2025-08-20T11:58:46.823Z',
    notificationsCount: 0,
    roleType: 'OWNER',
    inviterMemberId: '',
    invitedAt: null,
    permissions: [
      'CREATE_PERSONAL_CHAT_WITH_BOT',
      'CREATE_WORKSPACE_CHAT',
      'GRANT_ADMIN',
      'MANAGE_BOT',
      'GRANT_OWNER',
      'CANCEL_INVITE',
      'EDIT_WORKSPACE_NAME',
      'INVITE_TO_CHAT',
      'CREATE_SHARED_LINK',
      'REMOVE_MEMBER',
      'UPDATE_CONFIG',
      'CREATE_THREAD_IN_PERSONAL_CHAT',
      'REVOKE_ADMIN',
      'JOIN_CHAT',
      'REVOKE_OWNER',
      'SEARCH_CHATS',
      'INVITE_MEMBER',
      'TOGGLE_CONFERENCE_RECORDING',
      'MANAGE_WORKSPACE_SHARED_LINKS',
      'CREATE_THREAD_IN_WORKSPACE_CHAT',
    ],
    status: 'ACTIVE',
    memberId: 'k8YmHdFlxZ',
    ordernumber: 5,
  },
  {
    workspaceId: 'kmocYgPkXp',
    accountId: 'gtMoV7Isi0',
    workspace: {
      workspaceId: 'kmocYgPkXp',
      displayName: 'IT МРФ СЗ',
      subdomain: 'it-mrf-sz',
      createdAt: '2025-09-13T18:04:42.530Z',
      updatedAt: '2025-10-28T15:42:13.044Z',
      primaryAvatar: {
        avatarId: 'kmoc4Bff85',
        dominantColor: '8c8c8c',
      },
      membersCount: 8,
      type: 'REGULAR',
      organizationId: 'aRhF4Xy4Su',
      notifySettings: null,
    },
    createdAt: '2025-09-13T18:04:42.534Z',
    updatedAt: '2025-09-13T18:04:42.534Z',
    joinedAt: '2025-09-13T18:04:42.533Z',
    notificationsCount: 0,
    roleType: 'OWNER',
    inviterMemberId: '',
    invitedAt: null,
    permissions: [
      'CREATE_PERSONAL_CHAT_WITH_BOT',
      'CREATE_WORKSPACE_CHAT',
      'GRANT_ADMIN',
      'MANAGE_BOT',
      'GRANT_OWNER',
      'CANCEL_INVITE',
      'EDIT_WORKSPACE_NAME',
      'INVITE_TO_CHAT',
      'CREATE_SHARED_LINK',
      'REMOVE_MEMBER',
      'UPDATE_CONFIG',
      'CREATE_THREAD_IN_PERSONAL_CHAT',
      'REVOKE_ADMIN',
      'JOIN_CHAT',
      'REVOKE_OWNER',
      'SEARCH_CHATS',
      'INVITE_MEMBER',
      'TOGGLE_CONFERENCE_RECORDING',
      'MANAGE_WORKSPACE_SHARED_LINKS',
      'CREATE_THREAD_IN_WORKSPACE_CHAT',
    ],
    status: 'ACTIVE',
    memberId: 'kmocYhpkC9',
    ordernumber: 2,
  },
].toSorted((a, b) => a.ordernumber - b.ordernumber)
const chats = [
  {
    chat: {
      chatId: 'w:hj0pa9uLRI',
      memberIds: [
        'hj0pa6V9sW',
        'hpUC00dTW4',
        'hpUHAy8PGy',
        'hpa3C6ZL8r',
        'hpa68N22TJ',
        'hpaGl9k9An',
        'hpacBxSOe1',
        'hpcJNJbrLl',
        'hpn0kdi2wS',
        'hpoxDZRH5E',
        'hptMrBYzfV',
        'hsn7ti4WAL',
        'hsnIuOmKyf',
        'hsncMcKmkT',
        'i01UazIAwD',
        'i11dG9Wv1E',
        'i17SQKNP7Y',
        'i1BWp4n8Km',
        'i1CnZ3E3ge',
        'i1CnZ8Kq1o',
        'i1CnZDRcMy',
        'i1CnZHhbJw',
        'i1DsFA1cVk',
        'i3DX3Dqemn',
        'i3G6RUtMDx',
        'i6A6yvqA3l',
        'i6A8fhWke9',
        'igjBpjKmLQ',
        'kXBpiUu5Oz',
        'kXCybFj2P3',
        'lFsLTDHDOL',
      ],
      metadata: {
        workspace: {
          workspaceIds: [
            'hj0pa5vxcO',
          ],
          displayname: 'Общий',
          avatar: null,
          type: 'GENERAL',
          autoJoinNewMembers: true,
          announceChannel: false,
          description: '',
          memberCount: 0,
        },
      },
      lastReadMessageId: 'lgteLSGYHx',
      createdAt: '2025-05-22T09:30:30.150Z',
      updatedAt: '2025-10-17T13:00:59.686Z',
      archivedAt: null,
      archivedBy: '',
      memberActivities: [],
      isParticipated: true,
      hiddenAt: null,
      neverHide: false,
    },
    unreadCount: 0,
    updatedAt: null,
    pinnedAt: null,
    notifySettings: {
      rule: [
        'PERSONAL_MENTIONS',
        'CHANNEL_MENTIONS',
        'REACTIONS',
        'CHANNEL_CALLS',
      ],
      isMuted: false,
      muteExpiredAt: null,
    },
    folderName: '',
    role: 'CHAT_OWNER',
    permissions: [
      'CHANGE_ROLE',
      'ARCHIVE_CHAT',
      'RENAME_CHAT',
      'UPDATE_CONFIG',
      'KICK_FROM_CHAT',
      'SEND_MESSAGES_TO_ANNOUNCE_CHANNEL',
      'PIN_CHAT_MESSAGE',
      'SCHEDULE_CONFERENCE',
      'DELETE_CHAT_MESSAGE',
    ],
  },
  {
    chat: {
      chatId: 'w:hj0paGiiYq',
      memberIds: [
        'hj0pa6V9sW',
        'hpUC00dTW4',
        'hpUHAy8PGy',
      ],
      metadata: {
        workspace: {
          workspaceIds: [
            'hj0pa5vxcO',
          ],
          displayname: 'Frontend',
          avatar: null,
          type: 'PRIVATE',
          autoJoinNewMembers: false,
          announceChannel: false,
          description: '',
          memberCount: 0,
        },
      },
      lastReadMessageId: 'hwaZ4PFzmK',
      createdAt: '2025-05-22T09:30:30.174Z',
      updatedAt: '2025-05-23T04:33:22.945Z',
      archivedAt: null,
      archivedBy: '',
      memberActivities: [],
      isParticipated: true,
      hiddenAt: null,
      neverHide: false,
    },
    unreadCount: 0,
    updatedAt: null,
    pinnedAt: null,
    notifySettings: {
      rule: [
        'PERSONAL_MENTIONS',
        'CHANNEL_MENTIONS',
        'REACTIONS',
        'CHANNEL_CALLS',
      ],
      isMuted: false,
      muteExpiredAt: null,
    },
    folderName: '',
    role: 'CHAT_OWNER',
    permissions: [
      'CHANGE_ROLE',
      'ARCHIVE_CHAT',
      'RENAME_CHAT',
      'UPDATE_CONFIG',
      'KICK_FROM_CHAT',
      'SEND_MESSAGES_TO_ANNOUNCE_CHANNEL',
      'PIN_CHAT_MESSAGE',
      'SCHEDULE_CONFERENCE',
      'DELETE_CHAT_MESSAGE',
    ],
  },
  {
    chat: {
      chatId: 'w:hj0paNX5gO',
      memberIds: [
        'hj0pa6V9sW',
        'hpUC00dTW4',
        'hpUHAy8PGy',
        'hpa3C6ZL8r',
        'hpa68N22TJ',
        'hpaGl9k9An',
        'hpacBxSOe1',
        'hpcJNJbrLl',
        'hsn7ti4WAL',
        'hsnIuOmKyf',
        'hsncMcKmkT',
        'i01UazIAwD',
        'i11dG9Wv1E',
        'i17SQKNP7Y',
        'i1BWp4n8Km',
        'i1DsFA1cVk',
        'igjBpjKmLQ',
      ],
      metadata: {
        workspace: {
          workspaceIds: [
            'hj0pa5vxcO',
          ],
          displayname: 'Разработка',
          avatar: null,
          type: 'PRIVATE',
          autoJoinNewMembers: false,
          announceChannel: false,
          description: 'Команда разработки',
          memberCount: 0,
        },
      },
      lastReadMessageId: 'igjGbI1ASO',
      createdAt: '2025-05-22T09:30:30.198Z',
      updatedAt: '2025-09-17T07:26:56.210Z',
      archivedAt: null,
      archivedBy: '',
      memberActivities: [],
      isParticipated: true,
      hiddenAt: null,
      neverHide: false,
    },
    unreadCount: 0,
    updatedAt: '2025-05-26T06:45:19.480Z',
    pinnedAt: '2025-05-26T06:45:19.480Z',
    notifySettings: {
      rule: [
        'PERSONAL_MENTIONS',
        'CHANNEL_MENTIONS',
        'REACTIONS',
        'CHANNEL_CALLS',
      ],
      isMuted: false,
      muteExpiredAt: null,
    },
    folderName: '',
    role: 'CHAT_OWNER',
    permissions: [
      'CHANGE_ROLE',
      'ARCHIVE_CHAT',
      'RENAME_CHAT',
      'UPDATE_CONFIG',
      'KICK_FROM_CHAT',
      'SEND_MESSAGES_TO_ANNOUNCE_CHANNEL',
      'PIN_CHAT_MESSAGE',
      'SCHEDULE_CONFERENCE',
      'DELETE_CHAT_MESSAGE',
    ],
  },
  {
    chat: {
      chatId: 'w:hpSSbN9pZo',
      memberIds: [
        'hj0pa6V9sW',
        'hsn7ti4WAL',
        'i3G6RUtMDx',
      ],
      metadata: {
        workspace: {
          workspaceIds: [
            'hj0pa5vxcO',
          ],
          displayname: 'Тестирование 4.0',
          avatar: null,
          type: 'PUBLIC',
          autoJoinNewMembers: false,
          announceChannel: false,
          description: 'http://esuzfl-test.cod.sz.rt.ru',
          memberCount: 0,
        },
      },
      lastReadMessageId: 'i3GBtXRgHY',
      createdAt: '2025-05-26T06:42:46.284Z',
      updatedAt: '2025-09-17T07:26:56.210Z',
      archivedAt: null,
      archivedBy: '',
      memberActivities: [],
      isParticipated: true,
      hiddenAt: null,
      neverHide: false,
    },
    unreadCount: 0,
    updatedAt: '2025-06-02T05:28:05.600Z',
    pinnedAt: '2025-06-02T05:28:05.600Z',
    notifySettings: {
      rule: [
        'PERSONAL_MENTIONS',
        'CHANNEL_MENTIONS',
        'REACTIONS',
        'CHANNEL_CALLS',
      ],
      isMuted: false,
      muteExpiredAt: null,
    },
    folderName: '',
    role: 'CHAT_OWNER',
    permissions: [
      'CHANGE_ROLE',
      'ARCHIVE_CHAT',
      'RENAME_CHAT',
      'UPDATE_CONFIG',
      'KICK_FROM_CHAT',
      'SEND_MESSAGES_TO_ANNOUNCE_CHANNEL',
      'PIN_CHAT_MESSAGE',
      'SCHEDULE_CONFERENCE',
      'DELETE_CHAT_MESSAGE',
    ],
  },
  {
    chat: {
      chatId: 'w:hpSTGjCRWb',
      memberIds: [
        'hj0pa6V9sW',
        'hsn7ti4WAL',
        'i3G6RUtMDx',
      ],
      metadata: {
        workspace: {
          workspaceIds: [
            'hj0pa5vxcO',
          ],
          displayname: '🚀Запуск 4.0',
          avatar: null,
          type: 'PUBLIC',
          autoJoinNewMembers: false,
          announceChannel: false,
          description: 'http://esuzfl-new.cod.sz.rt.ru',
          memberCount: 0,
        },
      },
      lastReadMessageId: 'i3GBC3yn6v',
      createdAt: '2025-05-26T06:42:55.317Z',
      updatedAt: '2025-09-17T07:26:56.210Z',
      archivedAt: null,
      archivedBy: '',
      memberActivities: [],
      isParticipated: true,
      hiddenAt: null,
      neverHide: false,
    },
    unreadCount: 0,
    updatedAt: '2025-05-26T06:45:14.166Z',
    pinnedAt: '2025-05-26T06:45:14.166Z',
    notifySettings: {
      rule: [
        'PERSONAL_MENTIONS',
        'CHANNEL_MENTIONS',
        'REACTIONS',
        'CHANNEL_CALLS',
      ],
      isMuted: false,
      muteExpiredAt: null,
    },
    folderName: '',
    role: 'CHAT_OWNER',
    permissions: [
      'CHANGE_ROLE',
      'ARCHIVE_CHAT',
      'RENAME_CHAT',
      'UPDATE_CONFIG',
      'KICK_FROM_CHAT',
      'SEND_MESSAGES_TO_ANNOUNCE_CHANNEL',
      'PIN_CHAT_MESSAGE',
      'SCHEDULE_CONFERENCE',
      'DELETE_CHAT_MESSAGE',
    ],
  },
  {
    chat: {
      chatId: 'w:hpSYrHifWD',
      memberIds: [
        'hj0pa6V9sW',
        'hpaGl9k9An',
        'hpacBxSOe1',
      ],
      metadata: {
        workspace: {
          workspaceIds: [
            'hj0pa5vxcO',
          ],
          displayname: 'CI/CD',
          avatar: null,
          type: 'PRIVATE',
          autoJoinNewMembers: false,
          announceChannel: false,
          description: 'https://cicd-b2c.sz.rt.ru:8443/',
          memberCount: 0,
        },
      },
      lastReadMessageId: 'iou6LAAbLd',
      createdAt: '2025-05-26T06:44:11.013Z',
      updatedAt: '2025-09-17T07:26:56.210Z',
      archivedAt: null,
      archivedBy: '',
      memberActivities: [],
      isParticipated: true,
      hiddenAt: null,
      neverHide: false,
    },
    unreadCount: 0,
    updatedAt: null,
    pinnedAt: null,
    notifySettings: {
      rule: [
        'PERSONAL_MENTIONS',
        'CHANNEL_MENTIONS',
        'REACTIONS',
        'CHANNEL_CALLS',
      ],
      isMuted: false,
      muteExpiredAt: null,
    },
    folderName: '',
    role: 'CHAT_OWNER',
    permissions: [
      'CHANGE_ROLE',
      'ARCHIVE_CHAT',
      'RENAME_CHAT',
      'UPDATE_CONFIG',
      'KICK_FROM_CHAT',
      'SEND_MESSAGES_TO_ANNOUNCE_CHANNEL',
      'PIN_CHAT_MESSAGE',
      'SCHEDULE_CONFERENCE',
      'DELETE_CHAT_MESSAGE',
    ],
  },
  {
    chat: {
      chatId: 'w:hpSi860GQL',
      memberIds: [
        'hj0pa6V9sW',
        'hpUC00dTW4',
        'hpUHAy8PGy',
        'hpa3C6ZL8r',
        'hpa68N22TJ',
        'hpaGl9k9An',
        'hpacBxSOe1',
        'hpcJNJbrLl',
        'hpn0kdi2wS',
        'hpoxDZRH5E',
        'hptMrBYzfV',
        'hsn7ti4WAL',
        'hsnIuOmKyf',
        'hsncMcKmkT',
        'i01UazIAwD',
        'i11dG9Wv1E',
        'i17SQKNP7Y',
        'i1BWp4n8Km',
        'i1CnZ3E3ge',
        'i1CnZ8Kq1o',
        'i1CnZDRcMy',
        'i1CnZHhbJw',
        'i1DsFA1cVk',
        'i3DX3Dqemn',
        'i3G6RUtMDx',
        'i6A6yvqA3l',
        'i6A8fhWke9',
        'igjBpjKmLQ',
        'kXBpiUu5Oz',
        'kXCybFj2P3',
        'lFsLTDHDOL',
      ],
      metadata: {
        workspace: {
          workspaceIds: [
            'hj0pa5vxcO',
          ],
          displayname: '⚠️Перезагрузка',
          avatar: null,
          type: 'PUBLIC',
          autoJoinNewMembers: true,
          announceChannel: true,
          description: 'Уведомления об обновлении серверов',
          memberCount: 0,
        },
      },
      lastReadMessageId: 'hw8Ww9Y86j',
      createdAt: '2025-05-26T06:46:16.565Z',
      updatedAt: '2025-10-17T13:00:59.621Z',
      archivedAt: null,
      archivedBy: '',
      memberActivities: [],
      isParticipated: true,
      hiddenAt: null,
      neverHide: false,
    },
    unreadCount: 0,
    updatedAt: '2025-05-26T06:46:19.555Z',
    pinnedAt: '2025-05-26T06:46:19.555Z',
    notifySettings: {
      rule: [
        'PERSONAL_MENTIONS',
        'CHANNEL_MENTIONS',
        'REACTIONS',
        'CHANNEL_CALLS',
      ],
      isMuted: false,
      muteExpiredAt: null,
    },
    folderName: '',
    role: 'CHAT_OWNER',
    permissions: [
      'CHANGE_ROLE',
      'ARCHIVE_CHAT',
      'RENAME_CHAT',
      'UPDATE_CONFIG',
      'KICK_FROM_CHAT',
      'SEND_MESSAGES_TO_ANNOUNCE_CHANNEL',
      'PIN_CHAT_MESSAGE',
      'SCHEDULE_CONFERENCE',
      'DELETE_CHAT_MESSAGE',
    ],
  },
  {
    chat: {
      chatId: 'w:hw8dBZSI08',
      memberIds: [
        'hj0pa6V9sW',
        'hpcJNJbrLl',
      ],
      metadata: {
        workspace: {
          workspaceIds: [
            'hj0pa5vxcO',
          ],
          displayname: 'Массовая печать',
          avatar: null,
          type: 'PRIVATE',
          autoJoinNewMembers: false,
          announceChannel: false,
          description: '',
          memberCount: 0,
        },
      },
      lastReadMessageId: 'jAlCai1U3N',
      createdAt: '2025-05-30T07:18:31.610Z',
      updatedAt: '2025-09-17T07:26:56.210Z',
      archivedAt: null,
      archivedBy: '',
      memberActivities: [],
      isParticipated: true,
      hiddenAt: null,
      neverHide: false,
    },
    unreadCount: 0,
    updatedAt: null,
    pinnedAt: null,
    notifySettings: {
      rule: [
        'PERSONAL_MENTIONS',
        'CHANNEL_MENTIONS',
        'REACTIONS',
        'CHANNEL_CALLS',
      ],
      isMuted: false,
      muteExpiredAt: null,
    },
    folderName: '',
    role: 'CHAT_OWNER',
    permissions: [
      'CHANGE_ROLE',
      'ARCHIVE_CHAT',
      'RENAME_CHAT',
      'UPDATE_CONFIG',
      'KICK_FROM_CHAT',
      'SEND_MESSAGES_TO_ANNOUNCE_CHANNEL',
      'PIN_CHAT_MESSAGE',
      'SCHEDULE_CONFERENCE',
      'DELETE_CHAT_MESSAGE',
    ],
  },
  {
    chat: {
      chatId: 'w:hwaEIaaqie',
      memberIds: [
        'hj0pa6V9sW',
        'hsnIuOmKyf',
        'hsncMcKmkT',
      ],
      metadata: {
        workspace: {
          workspaceIds: [
            'hj0pa5vxcO',
          ],
          displayname: '👑Тимлиды',
          avatar: null,
          type: 'PRIVATE',
          autoJoinNewMembers: false,
          announceChannel: false,
          description: '',
          memberCount: 0,
        },
      },
      lastReadMessageId: 'ksid2d0dQe',
      createdAt: '2025-05-30T13:44:43.901Z',
      updatedAt: '2025-05-30T13:44:43.901Z',
      archivedAt: null,
      archivedBy: '',
      memberActivities: [],
      isParticipated: true,
      hiddenAt: null,
      neverHide: false,
    },
    unreadCount: 0,
    updatedAt: null,
    pinnedAt: null,
    notifySettings: {
      rule: [
        'PERSONAL_MENTIONS',
        'CHANNEL_MENTIONS',
        'REACTIONS',
        'CHANNEL_CALLS',
      ],
      isMuted: false,
      muteExpiredAt: null,
    },
    folderName: '',
    role: 'CHAT_OWNER',
    permissions: [
      'CHANGE_ROLE',
      'ARCHIVE_CHAT',
      'RENAME_CHAT',
      'UPDATE_CONFIG',
      'KICK_FROM_CHAT',
      'SEND_MESSAGES_TO_ANNOUNCE_CHANNEL',
      'PIN_CHAT_MESSAGE',
      'SCHEDULE_CONFERENCE',
      'DELETE_CHAT_MESSAGE',
    ],
  },
  {
    chat: {
      chatId: 'w:i1DzYVyjiL',
      memberIds: [
        'hj0pa6V9sW',
        'hpUC00dTW4',
        'hpUHAy8PGy',
        'hpa3C6ZL8r',
        'hpa68N22TJ',
        'hpaGl9k9An',
        'hpacBxSOe1',
        'hpcJNJbrLl',
        'hpn0kdi2wS',
        'hpoxDZRH5E',
        'hptMrBYzfV',
        'hsn7ti4WAL',
        'hsnIuOmKyf',
        'hsncMcKmkT',
        'i01UazIAwD',
        'i11dG9Wv1E',
        'i17SQKNP7Y',
        'i1BWp4n8Km',
        'i1CnZ3E3ge',
        'i1CnZ8Kq1o',
        'i1CnZDRcMy',
        'i3DX3Dqemn',
        'i3G6RUtMDx',
        'igjBpjKmLQ',
      ],
      metadata: {
        workspace: {
          workspaceIds: [
            'hj0pa5vxcO',
          ],
          displayname: 'Off-topic',
          avatar: null,
          type: 'PRIVATE',
          autoJoinNewMembers: false,
          announceChannel: false,
          description: 'Обсуждаем все, что не касается работы',
          memberCount: 0,
        },
      },
      lastReadMessageId: 'igjJZrpITR',
      createdAt: '2025-06-02T08:51:34.331Z',
      updatedAt: '2025-09-17T07:26:56.210Z',
      archivedAt: null,
      archivedBy: '',
      memberActivities: [],
      isParticipated: true,
      hiddenAt: null,
      neverHide: false,
    },
    unreadCount: 0,
    updatedAt: null,
    pinnedAt: null,
    notifySettings: {
      rule: [
        'PERSONAL_MENTIONS',
        'CHANNEL_MENTIONS',
        'REACTIONS',
        'CHANNEL_CALLS',
      ],
      isMuted: false,
      muteExpiredAt: null,
    },
    folderName: '',
    role: 'CHAT_MEMBER',
    permissions: [],
  },
  {
    chat: {
      chatId: 'w:lCxNmshkfI',
      memberIds: [
        'hj0pa6V9sW',
        'hpa3C6ZL8r',
        'hpn0kdi2wS',
        'hsnIuOmKyf',
        'hsncMcKmkT',
        'i3DX3Dqemn',
        'i3G6RUtMDx',
        'i6A6yvqA3l',
        'i6A8fhWke9',
        'kXBpiUu5Oz',
        'kXCybFj2P3',
        'lFsLTDHDOL',
      ],
      metadata: {
        workspace: {
          workspaceIds: [
            'hj0pa5vxcO',
          ],
          displayname: 'Релизы',
          avatar: null,
          type: 'PUBLIC',
          autoJoinNewMembers: true,
          announceChannel: false,
          description: '',
          memberCount: 0,
        },
      },
      lastReadMessageId: 'mcVH9D01hZ',
      createdAt: '2025-09-29T12:05:03.842Z',
      updatedAt: '2025-11-05T06:01:37.211Z',
      archivedAt: null,
      archivedBy: '',
      memberActivities: [],
      isParticipated: true,
      hiddenAt: null,
      neverHide: false,
    },
    unreadCount: 0,
    updatedAt: null,
    pinnedAt: null,
    notifySettings: {
      rule: [
        'PERSONAL_MENTIONS',
        'CHANNEL_MENTIONS',
        'REACTIONS',
        'CHANNEL_CALLS',
      ],
      isMuted: false,
      muteExpiredAt: null,
    },
    folderName: '',
    role: 'CHAT_MEMBER',
    permissions: [],
  },
]
const messages = [
  {
    type: 'USER_MESSAGE',
    messageId: 'jAlCai1U3N',
    parentId: '',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-15T11:16:18.244Z',
    updatedAt: '2025-07-15T11:16:18.244Z',
    content: [
      {
        markdown: '[@here](yuchat://esuz/channel/w:hw8dBZSI08/mention/here) вывел на тест и прод удаление тестовых нлс поштучно.',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j3ttEOuvzN',
    parentId: 'j3srBnv5iT',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-11T08:04:38.270Z',
    updatedAt: '2025-07-11T08:04:38.270Z',
    content: [
      {
        markdown: '[@channel](yuchat://esuz/channel/w:hw8dBZSI08/mention/channel)  вывел на прод свою часть.',
      },
    ],
    reactions: [
      {
        memberId: 'hpSZ47duF7',
        imageId: ':heart:',
      },
    ],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j3srBnv5iT',
    parentId: '',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-11T07:50:11Z',
    updatedAt: '2025-07-11T08:04:18.882Z',
    content: [
      {
        markdown: '~~Залил, нихера не законнектилось, эх...~~\n~~зачинил проксёй, но сабскрайб происходит раньше, чем коннект...~~\nи это зачинил',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j3sTR8z560',
    parentId: '',
    memberId: 'hpcJNJbrLl',
    createdAt: '2025-07-11T07:44:49.337Z',
    updatedAt: '2025-07-11T07:44:49.337Z',
    content: [
      {
        markdown: 'на деве работают',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j3sPv5MOrB',
    parentId: '',
    memberId: 'hpSZ47duF7',
    createdAt: '2025-07-11T07:44:01.708Z',
    updatedAt: '2025-07-11T07:44:01.708Z',
    content: [
      {
        markdown: 'чего там, работают сокеты? Могу прикручивать автоматические уведомлялки?',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j3qYtQDHn7',
    parentId: 'j2GxLuHwCO',
    memberId: 'hpcJNJbrLl',
    createdAt: '2025-07-11T07:18:03.989Z',
    updatedAt: '2025-07-11T07:18:03.989Z',
    content: [
      {
        markdown: 'можно лить.',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j2ZSgNXYO1',
    parentId: '',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-10T12:51:10.036Z',
    updatedAt: '2025-07-10T12:51:10.036Z',
    content: [
      {
        markdown: 'айди для отписки только передаю один и тот же везде, сейчас исправил, заливаю на тест',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j2ZBrq0Nqj',
    parentId: '',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-10T12:47:22.321Z',
    updatedAt: '2025-07-10T12:47:22.321Z',
    content: [
      {
        files: {
          file: [
            {
              fileId: 'j2ZBjEMVJR',
              metadata: {
                mimeType: 'image/png',
                fileSize: 196053,
                fileName: 'image.png',
              },
              createdAt: '2025-07-10T12:47:20.442Z',
              updatedAt: null,
              contentInfo: {
                imageContentInfo: {
                  width: 1878,
                  height: 673,
                },
              },
              previewFile: {
                fileId: 'j2ZBr9zkbB',
                metadata: {
                  mimeType: 'image/png',
                  fileSize: 119028,
                  fileName: 'preview.png',
                },
                createdAt: '2025-07-10T12:47:22.174Z',
                updatedAt: null,
                contentInfo: {
                  imageContentInfo: {
                    width: 800,
                    height: 286,
                  },
                },
                previewFile: null,
                status: 'READY',
                mediaType: 'IMAGE',
              },
              status: 'READY',
              mediaType: 'IMAGE',
            },
          ],
        },
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j2YWfUJFRI',
    parentId: 'j2IG5zgghF',
    memberId: 'hpcJNJbrLl',
    createdAt: '2025-07-10T12:38:04.392Z',
    updatedAt: '2025-07-10T12:38:04.392Z',
    content: [
      {
        markdown: '[https://ppr-test.sz.rt.ru/massprint/reports](https://ppr-test.sz.rt.ru/massprint/reports)\n[https://ppr-test.sz.rt.ru/massprint/xml](https://ppr-test.sz.rt.ru/massprint/xml)\nэто оно?\nчто-то не видно подписки тут',
      },
      {
        linkInfo: {
          linkInfo: [
            {
              url: 'https://ppr-test.sz.rt.ru/massprint/reports',
              title: '',
              description: '',
              image: null,
              siteName: '',
              siteIcons: [],
              processingState: 'IN_PROCESS',
            },
            {
              url: 'https://ppr-test.sz.rt.ru/massprint/xml',
              title: '',
              description: '',
              image: null,
              siteName: '',
              siteIcons: [],
              processingState: 'IN_PROCESS',
            },
          ],
        },
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j2IG5zgghF',
    parentId: '',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-10T08:50:26.070Z',
    updatedAt: '2025-07-10T08:50:26.070Z',
    content: [
      {
        markdown: 'Да, в таблице отчётов и таблице xml',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j2HxeKhEEy',
    parentId: 'j2GxLuHwCO',
    memberId: 'hpcJNJbrLl',
    createdAt: '2025-07-10T08:46:16.268Z',
    updatedAt: '2025-07-10T08:46:16.268Z',
    content: [
      {
        markdown: 'Ага, как победю, маякну.\n\nСаша, а на\nuser/{userId}/form/xml/reset  \nuser/{userId}/form/reports/reset\nподписка же должна отображаться тоже?',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j2GxLuHwCO',
    parentId: '',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-10T08:32:12.625Z',
    updatedAt: '2025-07-10T08:32:12.625Z',
    content: [
      {
        markdown: 'Потом скомандуете, когда заливать на прод',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j293ySA9qL',
    parentId: '',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-10T06:41:45.351Z',
    updatedAt: '2025-07-10T06:41:45.351Z',
    content: [
      {
        markdown: '[http://10.160.16.22:9091/mass-print-service/swagger-ui/index.html#/web-socket-controller/resetStreamsForm](http://10.160.16.22:9091/mass-print-service/swagger-ui/index.html#/web-socket-controller/resetStreamsForm)',
      },
      {
        files: {
          file: [
            {
              fileId: 'j293q1sEVd',
              metadata: {
                mimeType: 'image/png',
                fileSize: 17770,
                fileName: 'image.png',
              },
              createdAt: '2025-07-10T06:41:43.513Z',
              updatedAt: null,
              contentInfo: {
                imageContentInfo: {
                  width: 517,
                  height: 380,
                },
              },
              previewFile: {
                fileId: 'j293v1YbQ1',
                metadata: {
                  mimeType: 'image/png',
                  fileSize: 10677,
                  fileName: 'preview.png',
                },
                createdAt: '2025-07-10T06:41:44.603Z',
                updatedAt: null,
                contentInfo: {
                  imageContentInfo: {
                    width: 517,
                    height: 380,
                  },
                },
                previewFile: null,
                status: 'READY',
                mediaType: 'IMAGE',
              },
              status: 'READY',
              mediaType: 'IMAGE',
            },
            {
              fileId: 'j293ttA5A1',
              metadata: {
                mimeType: 'image/png',
                fileSize: 25307,
                fileName: 'image.png',
              },
              createdAt: '2025-07-10T06:41:44.355Z',
              updatedAt: null,
              contentInfo: {
                imageContentInfo: {
                  width: 680,
                  height: 254,
                },
              },
              previewFile: {
                fileId: 'j293x9Y4u0',
                metadata: {
                  mimeType: 'image/png',
                  fileSize: 15074,
                  fileName: 'preview.png',
                },
                createdAt: '2025-07-10T06:41:45.068Z',
                updatedAt: null,
                contentInfo: {
                  imageContentInfo: {
                    width: 680,
                    height: 254,
                  },
                },
                previewFile: null,
                status: 'READY',
                mediaType: 'IMAGE',
              },
              status: 'READY',
              mediaType: 'IMAGE',
            },
          ],
        },
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j290WKw6b3',
    parentId: '',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-10T06:40:58.583Z',
    updatedAt: '2025-07-10T06:40:58.583Z',
    content: [
      {
        markdown: 'Швайгер дёргаю, а сообщение в топик не летит)))',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j28tQwjY7E',
    parentId: 'j28qoHjDl3',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-10T06:39:22.610Z',
    updatedAt: '2025-07-10T06:39:22.610Z',
    content: [
      {
        markdown: 'С моей) С бэка автоматом ничего не летит, но можно швайгера пнуть',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j28rp8k8Wm',
    parentId: '',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-10T06:39:00.810Z',
    updatedAt: '2025-07-10T06:39:00.810Z',
    content: [
      {
        markdown: 'Подключение по сокету и подписька на топики. Дальше жду любое сообщение в эти топики, чтобы перезагрузить соответствующую таблицу',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j28qoHjDl3',
    parentId: '',
    memberId: 'hpcJNJbrLl',
    createdAt: '2025-07-10T06:38:47.081Z',
    updatedAt: '2025-07-10T06:38:47.081Z',
    content: [
      {
        markdown: 'заработало с твоей стороны или со стороны бэка?',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j28n0e6s2S',
    parentId: '',
    memberId: 'hpcJNJbrLl',
    createdAt: '2025-07-10T06:37:55.612Z',
    updatedAt: '2025-07-10T06:37:55.612Z',
    content: [
      {
        markdown: 'как это работает вообще? что заработало-то?',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j28kUJOBRR',
    parentId: '',
    memberId: 'hpcJNJbrLl',
    createdAt: '2025-07-10T06:37:21.466Z',
    updatedAt: '2025-07-10T06:37:21.466Z',
    content: [
      {
        markdown: 'подожди',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j28j1go6mP',
    parentId: '',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-10T06:37:01.671Z',
    updatedAt: '2025-07-10T06:37:01.671Z',
    content: [
      {
        markdown: 'Пожаловался и з аработало. Залил на тест 🙂',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j261TsSLZJ',
    parentId: '',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-10T05:59:12.733Z',
    updatedAt: '2025-07-10T05:59:12.733Z',
    content: [
      {
        markdown: 'Ладно. А можно я просто раз в секунду буду обновлять таблицу, если там есть хоть что-то синее в статусах? Сокеты вот прям очень плохо идут. То хттпс не жрут, то локально не подымаются... Хренова ссылка не генерится автоматически, а прокси не пашет для вебсокетных урлов 😃',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j22EMfDRdx',
    parentId: '',
    memberId: 'hpSZ47duF7',
    createdAt: '2025-07-10T05:06:08.733Z',
    updatedAt: '2025-07-10T05:06:08.733Z',
    content: [
      {
        markdown: 'надо руками, я пока не настраивал автомат)',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j1G7Fy49xI',
    parentId: '',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-09T17:52:50.794Z',
    updatedAt: '2025-07-09T17:55:57.245Z',
    content: [
      {
        markdown: 'Как проверять? Я запустил и молчок)) Там руками надо что-то делать?) Был "Подготовлено", я руками отменил, по топику нихрена)',
      },
      {
        files: {
          file: [
            {
              fileId: 'j1GKHC8V0a',
              metadata: {
                mimeType: 'image/png',
                fileSize: 3159,
                fileName: 'image.png',
              },
              createdAt: '2025-07-09T17:55:47.112Z',
              updatedAt: null,
              contentInfo: {
                imageContentInfo: {
                  width: 256,
                  height: 101,
                },
              },
              previewFile: {
                fileId: 'j1GKLTp2ky',
                metadata: {
                  mimeType: 'image/png',
                  fileSize: 2120,
                  fileName: 'preview.png',
                },
                createdAt: '2025-07-09T17:55:48.048Z',
                updatedAt: null,
                contentInfo: {
                  imageContentInfo: {
                    width: 256,
                    height: 101,
                  },
                },
                previewFile: null,
                status: 'READY',
                mediaType: 'IMAGE',
              },
              status: 'READY',
              mediaType: 'IMAGE',
            },
            {
              fileId: 'j1GKw4NEIb',
              metadata: {
                mimeType: 'image/png',
                fileSize: 18110,
                fileName: 'image.png',
              },
              createdAt: '2025-07-09T17:55:56.040Z',
              updatedAt: null,
              contentInfo: {
                imageContentInfo: {
                  width: 478,
                  height: 191,
                },
              },
              previewFile: {
                fileId: 'j1GL124PIX',
                metadata: {
                  mimeType: 'image/png',
                  fileSize: 10533,
                  fileName: 'preview.png',
                },
                createdAt: '2025-07-09T17:55:57.124Z',
                updatedAt: null,
                contentInfo: {
                  imageContentInfo: {
                    width: 478,
                    height: 191,
                  },
                },
                previewFile: null,
                status: 'READY',
                mediaType: 'IMAGE',
              },
              status: 'READY',
              mediaType: 'IMAGE',
            },
          ],
        },
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j1AuEheg6q',
    parentId: '',
    memberId: 'hpSZ47duF7',
    createdAt: '2025-07-09T16:39:56.377Z',
    updatedAt: '2025-07-09T16:39:56.377Z',
    content: [
      {
        markdown: 'похож',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j1Agx8VxpJ',
    parentId: 'j18qZm7inB',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-09T16:36:56.491Z',
    updatedAt: '2025-07-09T16:36:56.491Z',
    content: [
      {
        markdown: '```\nws://10.160.16.144:9091/mass-print-service/connect \n```\n\nтакой урл подключения?',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j18qZm7inB',
    parentId: '',
    memberId: 'hpSZ47duF7',
    createdAt: '2025-07-09T16:11:07.574Z',
    updatedAt: '2025-07-09T16:11:07.574Z',
    content: [
      {
        markdown: 'сервис тот же самый, mass-print',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j18mvnQzWj',
    parentId: 'j18kYFzjnd',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-09T16:10:18.215Z',
    updatedAt: '2025-07-09T16:10:18.215Z',
    content: [
      {
        markdown: 'Не так спросил, да. СЕРВИС)  всё как в есузе?',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j18kYFzjnd',
    parentId: 'j18YNqAO8W',
    memberId: 'hpSZ47duF7',
    createdAt: '2025-07-09T16:09:45.989Z',
    updatedAt: '2025-07-09T16:09:45.989Z',
    content: [
      {
        markdown: 'тест - 22, прод 114',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j18YNqAO8W',
    parentId: 'izLfVq8kMK',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-09T16:07:01.207Z',
    updatedAt: '2025-07-09T16:07:01.207Z',
    content: [
      {
        markdown: 'Сервак всё тот же сокетный?',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j17uFX2z1l',
    parentId: 'j17rsRi1B2',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-09T15:57:57.703Z',
    updatedAt: '2025-07-09T15:57:57.703Z',
    content: [
      {
        markdown: 'Передаю:\n\n```\n{\n    "userId": 61,\n    "rolesIds": [\n        3,\n        5,\n        6,\n        2,\n        3,\n        5,\n        6\n    ]\n}\n```',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'j17rsRi1B2',
    parentId: 'izLNdyJGoT',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-09T15:57:25.576Z',
    updatedAt: '2025-07-09T15:57:33.433Z',
    content: [
      {
        markdown: '```\n{\n    "timestamp": "2025-07-09T15:56:28.742+00:00",\n    "status": 500,\n    "error": "Internal Server Error",\n    "message": "Cannot invoke \\"java.util.List.stream()\\" because the return value of \\"rt.sz.esuz.b2c.mass.print.service.request.UserWithRoles.getRoleIds()\\" is null",\n    "path": "/mass-print-service/user"\n}\n```',
      },
    ],
    reactions: [
      {
        memberId: 'hpSZ47duF7',
        imageId: ':face_with_rolling_eyes:',
      },
    ],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'izNnEUStLE',
    parentId: 'izN0dbmJcG',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-08T14:45:03.898Z',
    updatedAt: '2025-07-08T14:45:03.898Z',
    content: [
      {
        markdown: 'Нет гейтвея, но есть реверсивный прокси. Но на каждый сервис бэка. Т.е., да, преобразует, но я не помню на какой. Кинет на бэк 22:9091',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'izN0dbmJcG',
    parentId: '',
    memberId: 'hpcJNJbrLl',
    createdAt: '2025-07-08T14:34:05.815Z',
    updatedAt: '2025-07-08T14:34:05.815Z',
    content: [
      {
        markdown: 'И ещё вопрос - у нас для it-сервисов нет гейтвея? Nginx преобразует запрос [https://ppr-test.sz.rt.ru/api/mass-print/tasks](https://ppr-test.sz.rt.ru/api/mass-print/tasks) в [http://10.160.16.22:9091/tasks](http://10.160.16.22:9091/tasks) ?',
      },
      {
        linkInfo: {
          linkInfo: [
            {
              url: 'https://ppr-test.sz.rt.ru/api/mass-print/tasks',
              title: '',
              description: '',
              image: null,
              siteName: '',
              siteIcons: [],
              processingState: 'IN_PROCESS',
            },
          ],
        },
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'izLfVq8kMK',
    parentId: 'iys43BQen3',
    memberId: 'hpcJNJbrLl',
    createdAt: '2025-07-08T14:15:20.113Z',
    updatedAt: '2025-07-08T14:15:20.113Z',
    content: [
      {
        markdown: 'можно потестить. Сообщение просто Object сделал.',
      },
    ],
    reactions: [
      {
        memberId: 'hpSZ47duF7',
        imageId: ':fire:',
      },
    ],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'izLTx507Xs',
    parentId: 'iys43BQen3',
    memberId: 'hpcJNJbrLl',
    createdAt: '2025-07-08T14:12:43.556Z',
    updatedAt: '2025-07-08T14:12:43.556Z',
    content: [
      {
        markdown: 'то есть\n/form/streams/reset\nuser/{userId}/form/xml/reset\nuser/{userId}/form/reports/reset\n? вроде бы так?',
      },
    ],
    reactions: [
      {
        memberId: 'hpSZ47duF7',
        imageId: ':+1:',
      },
    ],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'izLNdyJGoT',
    parentId: 'ixe4pd3cpN',
    memberId: 'hpcJNJbrLl',
    createdAt: '2025-07-08T14:11:18.129Z',
    updatedAt: '2025-07-08T14:11:18.129Z',
    content: [
      {
        markdown: 'сделал метод с массивом ролей [http://10.160.16.22:9091/mass-print-service/swagger-ui/index.html#/user-controller/updateUserWithRoles](http://10.160.16.22:9091/mass-print-service/swagger-ui/index.html#/user-controller/updateUserWithRoles)\nдля не существующих пользователей что должно быть? Возвращать, 500/нет такого пользователя?',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: {
      id: 't:izfUJCI4o4',
      messageCount: 1,
    },
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'izAMPDTe8e',
    parentId: 'ixUaHBNRyq',
    memberId: 'hpSZ47duF7',
    createdAt: '2025-07-08T11:37:05.562Z',
    updatedAt: '2025-07-08T11:37:05.562Z',
    content: [
      {
        markdown: 'пофиксил\n[http://10.160.16.22:9091/mass-print-service/swagger-ui/index.html#/param-controller/getParameterValue](http://10.160.16.22:9091/mass-print-service/swagger-ui/index.html#/param-controller/getParameterValue)',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'iysQ4K59eK',
    parentId: 'iysM1JqzPF',
    memberId: 'hpSZ47duF7',
    createdAt: '2025-07-08T07:26:02.037Z',
    updatedAt: '2025-07-08T07:26:02.037Z',
    content: [
      {
        markdown: 'да, давай аналогично',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'iysM1JqzPF',
    parentId: '',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-08T07:25:07.212Z',
    updatedAt: '2025-07-08T07:25:16.856Z',
    content: [
      {
        markdown: '> привязываем к юзеру\n\nКак в есузе? юзер в урле?',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'iys43BQen3',
    parentId: '',
    memberId: 'hpSZ47duF7',
    createdAt: '2025-07-08T07:21:03.859Z',
    updatedAt: '2025-07-08T07:21:03.859Z',
    content: [
      {
        markdown: 'ок, будут тогда\n\n```\n/form/streams/reset\n/form/xml/reset\n/form/reports/reset\n```\n\nstreams общая\nreports и xml привязываем к юзеру',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'iyr0ixNdA1',
    parentId: '',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-08T07:06:19.196Z',
    updatedAt: '2025-07-08T07:06:19.196Z',
    content: [
      {
        markdown: 'Разные. При уходе со страницы я буду отписываться от ненужных',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'iyqvkL9G53',
    parentId: '',
    memberId: 'hpSZ47duF7',
    createdAt: '2025-07-08T07:05:11.787Z',
    updatedAt: '2025-07-08T07:05:11.787Z',
    content: [
      {
        markdown: 'три разных топика или один, но разные сообщения?',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'iyqv7bknfF',
    parentId: '',
    memberId: 'hpSZ47duF7',
    createdAt: '2025-07-08T07:05:03.327Z',
    updatedAt: '2025-07-08T07:05:03.327Z',
    content: [
      {
        markdown: 'тебе надо обновлять форму "xml по НЛС", но в целом можно сделать и на потоки и на отчеты',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'iyqrJiEuf3',
    parentId: 'iypDJQWtwP',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-08T07:04:11.802Z',
    updatedAt: '2025-07-08T07:04:11.802Z',
    content: [
      {
        markdown: 'Какой хотите 🙂',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'iyqpSWDgtl',
    parentId: 'iynTHoteoy',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-08T07:03:46.641Z',
    updatedAt: '2025-07-08T07:03:46.641Z',
    content: [
      {
        markdown: 'Бэк.',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'iypDJQWtwP',
    parentId: '',
    memberId: 'hpSZ47duF7',
    createdAt: '2025-07-08T06:41:10.432Z',
    updatedAt: '2025-07-08T06:41:10.432Z',
    content: [
      {
        markdown: '[@Копосов Александр Денисович](yuchat://esuz/member/hj0pa6V9sW) все-таки давай прикрутим сокеты для масспринта\nЗадачка [https://ihelp.rt.ru/browse/ESZ-13819](https://ihelp.rt.ru/browse/ESZ-13819)\nКакой топик делаем?',
      },
      {
        linkInfo: {
          linkInfo: [
            {
              url: 'https://ihelp.rt.ru/browse/ESZ-13819',
              title: '',
              description: '',
              image: null,
              siteName: '',
              siteIcons: [],
              processingState: 'IN_PROCESS',
            },
          ],
        },
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'iynTHoteoy',
    parentId: '',
    memberId: 'hpcJNJbrLl',
    createdAt: '2025-07-08T06:16:47.520Z',
    updatedAt: '2025-07-08T06:16:47.520Z',
    content: [
      {
        markdown: 'Саша, подскажи, Session-Id в массПринте ты шлёшь или бэк генерирует?',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'ixe6vjIm6j',
    parentId: '',
    memberId: 'hpcJNJbrLl',
    createdAt: '2025-07-07T13:38:11.863Z',
    updatedAt: '2025-07-07T13:38:11.863Z',
    content: [
      {
        markdown: 'ок',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'ixe4pd3cpN',
    parentId: '',
    memberId: 'hpSZ47duF7',
    createdAt: '2025-07-07T13:37:43.446Z',
    updatedAt: '2025-07-07T13:37:43.446Z',
    content: [
      {
        markdown: '[@Мазур Константин Константинович](yuchat://esuz/member/hpcJNJbrLl) сделаешь всё как Саня просит? я тут пока в другую задачу вник)',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
  {
    type: 'USER_MESSAGE',
    messageId: 'ixcwZcTvdJ',
    parentId: 'iUpWPWnmQT',
    memberId: 'hj0pa6V9sW',
    createdAt: '2025-07-07T13:21:51.993Z',
    updatedAt: '2025-07-07T13:21:57.712Z',
    content: [
      {
        markdown: 'А чем не устроила предложенная мной модель? Выглядела ничо так 😃\n\n```\n{\n  userId: number\n  rolesIds: number[]\n  replaceUserId: null || number\n} \n```',
      },
    ],
    reactions: [],
    removedAt: null,
    removedByMemberId: '',
    thread: null,
    pinnedAt: null,
    pollVotes: null,
    isHidden: false,
  },
]

function getInitials(name: string) {
  const parts = name.split(' ')
  const first = parts[0]
  const last = parts[parts.length - 1]
  if (first && last) {
    return `${first[0]}${last[0]}`.toUpperCase()
  }
  if (first) {
    return `${first[0]}`.toUpperCase()
  }
  return '??'
}

const activeWorkspaceId = 'hj0pa5vxcO'
const activeWorkspace = computed(() => workspaces.find(i => i.workspaceId === activeWorkspaceId))
const activeChatId = 'w:hj0paGiiYq'
const activeChat = computed(() => chats.find(i => i.chat.chatId === activeChatId))
</script>

<template>
  <div class="flex h-full">
    <aside class="bg-black/10 p-3">
      <ul class="w-10 flex flex-col gap-5">
        <li
          v-for="item in workspaces"
          :key="item.workspaceId"
          :title="item.workspace.displayName"
          class="cursor-pointer border-1 border-black/5 overflow-hidden rounded-md flex items-center justify-center hover:outline-purple transition-all outline-transparent outline-3 size-9"
          :class="{
            'outline-purple': item.workspaceId === activeWorkspaceId,
            'bg-black/10 ': !item.workspace.primaryAvatar,
          }"
        >
          <img
            v-if="item.workspace.primaryAvatar"
            :src="`https://yuchat.rt.ru/api/avatar.download/${item.workspace.primaryAvatar?.avatarId}/192`"
            :alt="item.workspace.displayName"
            class="size-full rounded-[4px]"
          >
          <span v-else class="text-[16px] font-bold">
            {{ getInitials(item.workspace.displayName) }}
          </span>
        </li>
      </ul>
    </aside>

    <aside class="w-30%">
      <template v-if="activeWorkspace">
        <h3 class="text-h3 font-bold border-b-1 border-black/7 p-3 mb-3">
          {{ activeWorkspace.workspace.displayName }}
        </h3>

        <!--        <div class="p-3"> -->
        <!--          calls -->
        <!--        </div> -->

        <p class="text-[12px] color-black font-medium px-3 mb-0 pb-0">
          Каналы
        </p>
        <ul class="w-full flex flex-col gap-0 p-3">
          <li
            v-for="item in chats"
            :key="item.chat.chatId"
            :title="item.chat.metadata?.workspace?.displayname"
            class="px-1 py-[6px] w-full cursor-pointer border-black/5 rounded-md flex items-center hover:bg-black/7 transition-all gap-x-2"
            :class="{
              'bg-purple/10': item.chat.chatId === activeChatId,
            }"
          >
            <i class="size-6 p-1 bg-black/7 rounded-sm">
              <svg v-if="item.chat.metadata?.workspace?.type === 'PRIVATE'" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 16" focusable="false" class="chakra-icon css-1qjdtzc"><path fill="currentColor" d="M5.213 13.754h5.754c.814 0 1.213-.404 1.213-1.29V8.019c0-.797-.328-1.207-1.002-1.272V5.328C11.178 3.09 9.666 2 8.09 2S5.002 3.09 5.002 5.328v1.436C4.363 6.852 4 7.256 4 8.018v4.447c0 .885.398 1.289 1.213 1.289m1.055-8.525c0-1.284.814-2.004 1.822-2.004s1.822.72 1.822 2.004v1.505l-3.644.006z" /></svg>
              <svg v-else xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 16" focusable="false" class="chakra-icon css-144u592"><path fill="currentColor" fill-rule="evenodd" d="M12 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0m2 7.75C14 14 10 14 9 14s-5 0-5-1.25C4 10.875 6.239 9 9 9s5 1.875 5 3.75m-13 .052c0-1.617 1.737-3.234 4.013-3.541q-.082.06-.162.121C3.787 10.21 3 11.411 3 12.75c0 .51.224.886.503 1.156C2.25 13.78 1 13.486 1 12.802m5.537-4.65A4 4 0 0 1 5 5c0-.945.328-1.814.876-2.499L5.792 2.5a2.875 2.875 0 1 0 .745 5.652" clip-rule="evenodd" /></svg>
            </i>
            <span class="text-[14px] font-medium">
              {{ item.chat.metadata?.workspace?.displayname }}
            </span>
          </li>
        </ul>
      </template>
      <h3 v-else class="text-h3">
        Выберите пространство
      </h3>
    </aside>

    <main class="w-full border-l-1 border-black/7 h-full">
      <template v-if="activeChat">
        <h3 class="text-h3 font-bold border-b-1 border-black/7 p-3 mb-3">
          {{ activeChat.chat.metadata?.workspace?.displayname }}
        </h3>

        <ul class="w-full flex flex-col-reverse gap-0 p-3 overflow-auto h-[calc(100%-100px)]">
          <li
            v-for="item in messages"
            :key="`${item.messageId}`"
            class="p-3 w-full cursor-pointer border-black/5 rounded-md flex items-start hover:bg-black/7 transition-all gap-x-3"
          >
            <div class="size-8 min-w-8 rounded-full text-[14px] font-medium bg-black/7 flex items-center justify-center">
              ЮН
            </div>
            <div class="text-[14px] flex flex-col">
              <h5 class="text-[15px] font-medium">
                Васечкин Юрий Николаич
              </h5>
              <p v-for="(row, index) in item.content ?? []" :key="item.messageId + index">
                {{ row.markdown }}
              </p>
            </div>
          </li>
        </ul>
      </template>
      <h3 v-else class="text-h3">
        Выберите канал
      </h3>
    </main>

    <aside class="w-25%">
      treads
    </aside>
  </div>
</template>
